const artworks = [
  {
    id: 1,
    image: "/wildandart/silentsavannah.jpg",
    title: "Silent Savannah",
    artist: "Amara Njoroge",
    medium: "Oil",
    price: 250,
    location: "Nairobi, Kenya",
    description: "An oil painting capturing the serene beauty of the savannah.",
  },
  {
    id: 2,
    image: "/wildandart/wingsoffreedom.webp",
    title: "Wings of Freedom",
    artist: "David Kimani",
    medium: "Photo Print",
    price: 120,
    location: "Mombasa, Kenya",
    description: "A stunning photo print of a bird in mid-flight.",
  },
  {
    id: 3,
    image: "/wildandart/digitaljungle.jpg",
    title: "Digital Jungle",
    artist: "Lina Mwangi",
    medium: "Digital",
    price: 60,
    location: "Online Download",
    description:
      "A digital artwork blending abstract design with jungle motifs.",
  },
  {
    id: 4,
    image: "/wildandart/echoesofthewild.jpg",
    title: "Echoes of the Wild",
    artist: "Samuel Otieno",
    medium: "Watercolor",
    price: 180,
    location: "Kisumu, Kenya",
    description: "Watercolor painting of elephants at the watering hole.",
  },
  {
    id: 5,
    image: "/wildandart/urbansafari.webp",
    title: "Urban Safari",
    artist: "Fatma Hassan",
    medium: "Acrylic",
    price: 300,
    location: "Nairobi, Kenya",
    description: "Acrylic piece contrasting wildlife with urban landscapes.",
  },
  {
    id: 6,
    image: "/wildandart/serengetisunrise.jpg",
    title: "Serengeti Dreams",
    artist: "Willis Amani",
    medium: "Oil",
    price: 400,
    location: "Arusha, Tanzania",
    description: "A vibrant oil painting of the Serengeti at dawn.",
  },
];

export default artworks;
